// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VovinamApi.Data;

#nullable disable

namespace vovinam_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VovinamApi.Models.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamSinh")
                        .HasColumnType("int");

                    b.Property<int>("NhomTuoi")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("VovinamApi.Models.BanThuKyAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("BanThuKyAccounts");
                });

            modelBuilder.Entity("VovinamApi.Models.CompetitionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<int?>("HangCan")
                        .HasColumnType("int");

                    b.Property<int>("HinhThucThi")
                        .HasColumnType("int");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<int>("NhomTuoi")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiGianBaiGiay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("VovinamApi.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AthleteBlueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AthleteRedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LyDoKetThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NextMatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NextMatchSlot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NguoiThangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteBlueId");

                    b.HasIndex("AthleteRedId");

                    b.HasIndex("EventId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("VovinamApi.Models.MatchLiveSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapNhatLuc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MatchLiveSnapshots");
                });

            modelBuilder.Entity("VovinamApi.Models.PerformanceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("TeamId");

                    b.ToTable("PerformanceOrders");
                });

            modelBuilder.Entity("VovinamApi.Models.QuyenJudgeScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChiTietJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Diem")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GiamKhaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenGiamKhao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("EventId");

                    b.HasIndex("TeamId");

                    b.ToTable("QuyenJudgeScores");
                });

            modelBuilder.Entity("VovinamApi.Models.QuyenLuotHoanThanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("EventId");

                    b.HasIndex("TeamId");

                    b.ToTable("QuyenLuotHoanThanhs");
                });

            modelBuilder.Entity("VovinamApi.Models.QuyenResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Diem")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DiemTru")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("EventId");

                    b.HasIndex("TeamId");

                    b.ToTable("QuyenResults");
                });

            modelBuilder.Entity("VovinamApi.Models.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("AthleteId", "EventId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("VovinamApi.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("VovinamApi.Models.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChoPhepDongHangBaQuyen")
                        .HasColumnType("bit");

                    b.Property<bool>("ChoPhepHiepPhu")
                        .HasColumnType("bit");

                    b.Property<int>("HeSoBac")
                        .HasColumnType("int");

                    b.Property<int>("HeSoDong")
                        .HasColumnType("int");

                    b.Property<int>("HeSoVang")
                        .HasColumnType("int");

                    b.Property<int>("SoSan")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("VovinamApi.Models.TrongTai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourtId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThuTuGiamDinh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "ThuTuGiamDinh")
                        .IsUnique()
                        .HasFilter("[ThuTuGiamDinh] IS NOT NULL");

                    b.ToTable("TrongTais");
                });

            modelBuilder.Entity("VovinamApi.Models.Athlete", b =>
                {
                    b.HasOne("VovinamApi.Models.Team", "Team")
                        .WithMany("Athletes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VovinamApi.Models.Match", b =>
                {
                    b.HasOne("VovinamApi.Models.Athlete", "AthleteBlue")
                        .WithMany()
                        .HasForeignKey("AthleteBlueId");

                    b.HasOne("VovinamApi.Models.Athlete", "AthleteRed")
                        .WithMany()
                        .HasForeignKey("AthleteRedId");

                    b.HasOne("VovinamApi.Models.CompetitionEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteBlue");

                    b.Navigation("AthleteRed");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("VovinamApi.Models.MatchLiveSnapshot", b =>
                {
                    b.HasOne("VovinamApi.Models.Match", null)
                        .WithOne()
                        .HasForeignKey("VovinamApi.Models.MatchLiveSnapshot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VovinamApi.Models.PerformanceOrder", b =>
                {
                    b.HasOne("VovinamApi.Models.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId");

                    b.HasOne("VovinamApi.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Athlete");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VovinamApi.Models.QuyenJudgeScore", b =>
                {
                    b.HasOne("VovinamApi.Models.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VovinamApi.Models.CompetitionEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VovinamApi.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VovinamApi.Models.QuyenLuotHoanThanh", b =>
                {
                    b.HasOne("VovinamApi.Models.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VovinamApi.Models.CompetitionEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VovinamApi.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VovinamApi.Models.QuyenResult", b =>
                {
                    b.HasOne("VovinamApi.Models.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VovinamApi.Models.CompetitionEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VovinamApi.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VovinamApi.Models.Registration", b =>
                {
                    b.HasOne("VovinamApi.Models.Athlete", "Athlete")
                        .WithMany("Registrations")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VovinamApi.Models.CompetitionEvent", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("VovinamApi.Models.Athlete", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("VovinamApi.Models.CompetitionEvent", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("VovinamApi.Models.Team", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
